### ISSUE TITLE
non-specific scoping in query for message board

### ISSUE THREAD

**Issue by saturnflyer** [jayroh/thredded#115]
I'm working on https://github.com/saturnflyer/purple_door/tree/forum and ran into this error where the `name` column seems to be not scoped to the appropriate table.

```
PG::UndefinedColumn: ERROR:  column "name" does not exist
LINE 1: ...thredded_roles"."messageboard_id" = $1 AND (lower(name) IN (...
                                                             ^
: SELECT "users"."id" AS t0_r0, "users"."email" AS t0_r1, "users"."encrypted_password" AS t0_r2, "users"."reset_password_token" AS t0_r3, "users"."reset_password_sent_at" AS t0_r4, "users"."remember_created_at" AS t0_r5, "users"."sign_in_count" AS t0_r6, "users"."current_sign_in_at" AS t0_r7, "users"."last_sign_in_at" AS t0_r8, "users"."current_sign_in_ip" AS t0_r9, "users"."last_sign_in_ip" AS t0_r10, "users"."created_at" AS t0_r11, "users"."updated_at" AS t0_r12, "users"."permissions" AS t0_r13, "users"."first_name" AS t0_r14, "users"."last_name" AS t0_r15, "users"."birthdate" AS t0_r16, "users"."profile_image" AS t0_r17, "users"."superuser" AS t0_r18, "thredded_user_preferences"."id" AS t1_r0, "thredded_user_preferences"."user_id" AS t1_r1, "thredded_user_preferences"."time_zone" AS t1_r2, "thredded_user_preferences"."created_at" AS t1_r3, "thredded_user_preferences"."updated_at" AS t1_r4, "thredded_user_details"."id" AS t2_r0, "thredded_user_details"."user_id" AS t2_r1, "thredded_user_details"."latest_activity_at" AS t2_r2, "thredded_user_details"."posts_count" AS t2_r3, "thredded_user_details"."topics_count" AS t2_r4, "thredded_user_details"."superadmin" AS t2_r5, "thredded_user_details"."created_at" AS t2_r6, "thredded_user_details"."updated_at" AS t2_r7 FROM "users" LEFT OUTER JOIN "thredded_user_preferences" ON "thredded_user_preferences"."user_id" = "users"."id" LEFT OUTER JOIN "thredded_user_details" ON "thredded_user_details"."user_id" = "users"."id" INNER JOIN "thredded_roles" ON "users"."id" = "thredded_roles"."user_id" WHERE "thredded_roles"."messageboard_id" = $1 AND (lower(name) IN (NULL))
```

I'm not sure how to figure out exactly what is wrong ¯\\\_(ツ)\_/¯

**Comment by jayroh** [comment]
Hey Jim! Is there a particular controller and/or method that this could be attributed to in the stack trace? Is it the `current_user` method?

**Comment by glebm** [comment]
I think it is generated here https://github.com/jayroh/thredded/blob/master/lib/thredded/case_insensitive_string_finder/postgresql_builder.rb

**Comment by jayroh** [comment]
Awesome. Thank you @glebm

**Comment by glebm** [comment]
Since I can't submit PRs here yet:

* The relevant methods are [`quote_table_name`](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/Quoting.html#method-i-quote_table_name) and [`quote_column_name`].
* Minor bug with lowercase can be fixed like this: http://stackoverflow.com/questions/28300595/how-to-perform-a-case-insensitive-search-when-lowerfield-on-the-database-is-no/28300665#28300665

**Comment by saturnflyer** [comment]
I played with this a bit and tried to do something like this (while crossing my fingers)
```ruby
require 'thredded/case_insensitive_string_finder/postgresql_builder'
module Thredded
  class CaseInsensitiveStringFinder
    module PostgreSQLBuilder
      # @param [String, Array<String>] values
      # @return [ActiveRecord::Relation]
      def find(values)
        quoted_selector = [ActiveRecord::Base.connection.quote_table_name(scope.table_name),
                          ActiveRecord::Base.connection.quote_column_name(column)].join('.')
        scope#.where("lower(#{quoted_selector}) IN (?)", Array(values).map{|v| "lower(#{v})"})
      end
    end
  end
end
```
Of course, that didn't work. It took the table name from the scope which was `users` and I _think_ that thredded wants it to use `thredded_messageboards` but I'm not sure how to programmatically achieve that.

**Comment by jayroh** [comment]
What's the stack trace on that, @saturnflyer? Would love to be able to replicate here

**Comment by saturnflyer** [comment]
stack:
```
ActiveRecord::StatementInvalid - PG::UndefinedColumn: ERROR:  column "name" does not exist
LINE 1: ...thredded_roles"."messageboard_id" = $1 AND (lower(name) IN (...
                                                             ^
: SELECT "users"."id" AS t0_r0, "users"."email" AS t0_r1, "users"."encrypted_password" AS t0_r2, "users"."reset_password_token" AS t0_r3, "users"."reset_password_sent_at" AS t0_r4, "users"."remember_created_at" AS t0_r5, "users"."sign_in_count" AS t0_r6, "users"."current_sign_in_at" AS t0_r7, "users"."last_sign_in_at" AS t0_r8, "users"."current_sign_in_ip" AS t0_r9, "users"."last_sign_in_ip" AS t0_r10, "users"."created_at" AS t0_r11, "users"."updated_at" AS t0_r12, "users"."permissions" AS t0_r13, "users"."first_name" AS t0_r14, "users"."last_name" AS t0_r15, "users"."birthdate" AS t0_r16, "users"."profile_image" AS t0_r17, "users"."superuser" AS t0_r18, "thredded_user_preferences"."id" AS t1_r0, "thredded_user_preferences"."user_id" AS t1_r1, "thredded_user_preferences"."time_zone" AS t1_r2, "thredded_user_preferences"."created_at" AS t1_r3, "thredded_user_preferences"."updated_at" AS t1_r4, "thredded_user_details"."id" AS t2_r0, "thredded_user_details"."user_id" AS t2_r1, "thredded_user_details"."latest_activity_at" AS t2_r2, "thredded_user_details"."posts_count" AS t2_r3, "thredded_user_details"."topics_count" AS t2_r4, "thredded_user_details"."superadmin" AS t2_r5, "thredded_user_details"."created_at" AS t2_r6, "thredded_user_details"."updated_at" AS t2_r7 FROM "users" LEFT OUTER JOIN "thredded_user_preferences" ON "thredded_user_preferences"."user_id" = "users"."id" LEFT OUTER JOIN "thredded_user_details" ON "thredded_user_details"."user_id" = "users"."id" INNER JOIN "thredded_roles" ON "users"."id" = "thredded_roles"."user_id" WHERE "thredded_roles"."messageboard_id" = $1 AND (lower(name) IN (NULL)):
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract_adapter.rb:462:in `translate_exception_class'
  activerecord (4.2.3) lib/active_record/connection_adapters/postgresql_adapter.rb:643:in `rescue in prepare_statement'
  activerecord (4.2.3) lib/active_record/connection_adapters/postgresql_adapter.rb:640:in `prepare_statement'
  activerecord (4.2.3) lib/active_record/connection_adapters/postgresql_adapter.rb:600:in `exec_cache'
  activerecord (4.2.3) lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
  activerecord (4.2.3) lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  activerecord (4.2.3) lib/active_record/relation/finder_methods.rb:356:in `find_with_associations'
  activerecord (4.2.3) lib/active_record/relation.rb:638:in `exec_queries'
  activerecord (4.2.3) lib/active_record/association_relation.rb:32:in `exec_queries'
  activerecord (4.2.3) lib/active_record/relation.rb:514:in `load'
  activerecord (4.2.3) lib/active_record/relation.rb:243:in `to_a'
  activerecord (4.2.3) lib/active_record/relation/delegation.rb:46:in `each'
   () Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/lib/thredded/at_users.rb:7:in `render'
   () Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/lib/html/pipeline/at_mention_filter.rb:13:in `call'
  html-pipeline (2.0) lib/html/pipeline/filter.rb:130:in `call'
  html-pipeline (2.0) lib/html/pipeline.rb:121:in `block in perform_filter'
  html-pipeline (2.0) lib/html/pipeline.rb:159:in `instrument'
  html-pipeline (2.0) lib/html/pipeline.rb:120:in `perform_filter'
  html-pipeline (2.0) lib/html/pipeline.rb:106:in `block (2 levels) in call'
  html-pipeline (2.0) lib/html/pipeline.rb:105:in `block in call'
  html-pipeline (2.0) lib/html/pipeline.rb:159:in `instrument'
  html-pipeline (2.0) lib/html/pipeline.rb:103:in `call'
   () Users/jim/.gem/ruby/2.2.2/bundler/gems/thredded-39da38c744ab/app/models/thredded/post.rb:65:in `filtered_content'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/delegate.rb:87:in `method_missing'
  app/themes/default/views/thredded/posts/_post.html.erb:13:in `block (2 levels) in _app_themes_default_views_thredded_posts__post_html_erb__873423882954468017_70232170300640'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.3) lib/action_view/helpers/record_tag_helper.rb:101:in `content_tag_for_single_record'
  actionview (4.2.3) lib/action_view/helpers/record_tag_helper.rb:87:in `block in content_tag_for'
  actionview (4.2.3) lib/action_view/helpers/record_tag_helper.rb:86:in `content_tag_for'
  app/themes/default/views/thredded/posts/_post.html.erb:4:in `block in _app_themes_default_views_thredded_posts__post_html_erb__873423882954468017_70232170300640'
  actionview (4.2.3) lib/action_view/helpers/cache_helper.rb:117:in `cache'
  app/themes/default/views/thredded/posts/_post.html.erb:1:in `_app_themes_default_views_thredded_posts__post_html_erb__873423882954468017_70232170300640'
  actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:143:in `render'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:436:in `block in collection_with_template'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:432:in `collection_with_template'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:324:in `render_collection'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:306:in `block in render'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:305:in `render'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.3) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  app/themes/default/views/thredded/topics/show.html.erb:26:in `block in _app_themes_default_views_thredded_topics_show_html_erb___490319104640148341_70232173551100'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.3) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.3) lib/action_view/helpers/record_tag_helper.rb:101:in `content_tag_for_single_record'
  actionview (4.2.3) lib/action_view/helpers/record_tag_helper.rb:87:in `block in content_tag_for'
  actionview (4.2.3) lib/action_view/helpers/record_tag_helper.rb:86:in `content_tag_for'
  app/themes/default/views/thredded/topics/show.html.erb:14:in `_app_themes_default_views_thredded_topics_show_html_erb___490319104640148341_70232173551100'
  actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:143:in `render'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.3) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.3) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.3) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.3) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/jim/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by glebm** [comment]
Instead of using scope.table_name try Thredded.user_class.table_name

**Comment by glebm** [comment]
Values need to be escaped as well.

**Comment by jayroh** [comment]
Fixed with changes detailed here https://github.com/jayroh/thredded/commit/ff2141d39dc60e249ea1d879721e2954c3211fe5
