### ISSUE TITLE
errors with default template files

### ISSUE THREAD

**Issue by saturnflyer** [jayroh/thredded#121]
I'm currently assuming that the generated template files are the same in the tests for this engine (I didn't dig but only found 1 reference).

This commit https://github.com/jayroh/thredded/commit/8ba5c3e5c08dd42620f2d9b4a32f9e2b099daa62 added a file which depends upon the engine being mounted as `thredded`
In my project I mounted it as `forum` and so the `search.html.erb` file blows up when it gets to `<li><%= link_to 'Forums', thredded.root_path %></li>` in `app/views/thredded/topics/search.html.erb`
It looks like it might be in other places too.

**Comment by saturnflyer** [comment]
This is actually a larger problem than just the template files. 

The engine's application controller is making the assumption that it is mounted as `thredded` here https://github.com/jayroh/thredded/blob/e124c1b4514124c5c7062ea93cac103094961fb6/app/controllers/thredded/application_controller.rb#L19
which leads to this error (from my heroku app):

```
2015-08-04T09:10:40.558108+00:00 app[web.1]: NameError (undefined local variable or method `thredded' for #<Thredded::MessageboardsController:0x007f27a75df090>):
2015-08-04T09:10:40.558100+00:00 app[web.1]: F, [2015-08-04T09:10:40.557886 #173] FATAL -- :
2015-08-04T09:10:40.558112+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:114:in `instance_exec'
2015-08-04T09:10:40.558119+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
2015-08-04T09:10:40.558114+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:114:in `block in handler_for_rescue'
2015-08-04T09:10:40.558110+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/bundler/gems/thredded-39da38c744ab/app/controllers/thredded/application_controller.rb:19:in `block in <class:ApplicationController>'
2015-08-04T09:10:40.558122+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
2015-08-04T09:10:40.558115+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:80:in `call'
2015-08-04T09:10:40.558120+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:15:in `rescue_with_handler'
2015-08-04T09:10:40.558133+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
2015-08-04T09:10:40.558127+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
2015-08-04T09:10:40.558138+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
2015-08-04T09:10:40.558146+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2015-08-04T09:10:40.558139+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2015-08-04T09:10:40.558134+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-08-04T09:10:40.558156+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
2015-08-04T09:10:40.558149+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
2015-08-04T09:10:40.558175+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
2015-08-04T09:10:40.558153+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
2015-08-04T09:10:40.558168+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
2015-08-04T09:10:40.558183+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
2015-08-04T09:10:40.558160+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2015-08-04T09:10:40.558164+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
2015-08-04T09:10:40.558129+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2015-08-04T09:10:40.558143+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2015-08-04T09:10:40.558171+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
2015-08-04T09:10:40.558179+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2015-08-04T09:10:40.558188+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
2015-08-04T09:10:40.558187+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
2015-08-04T09:10:40.558224+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
2015-08-04T09:10:40.558192+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
2015-08-04T09:10:40.558271+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2015-08-04T09:10:40.558195+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
2015-08-04T09:10:40.558279+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
2015-08-04T09:10:40.558283+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
2015-08-04T09:10:40.558269+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:51:in `serve'
2015-08-04T09:10:40.558276+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
2015-08-04T09:10:40.558277+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
2015-08-04T09:10:40.558288+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
2015-08-04T09:10:40.558295+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
2015-08-04T09:10:40.558286+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
2015-08-04T09:10:40.558292+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
2015-08-04T09:10:40.558299+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2015-08-04T09:10:40.558306+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
2015-08-04T09:10:40.558302+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2015-08-04T09:10:40.558317+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
2015-08-04T09:10:40.558334+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
2015-08-04T09:10:40.558342+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
2015-08-04T09:10:40.558336+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2015-08-04T09:10:40.558337+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
2015-08-04T09:10:40.558343+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2015-08-04T09:10:40.558346+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2015-08-04T09:10:40.558351+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2015-08-04T09:10:40.558345+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
2015-08-04T09:10:40.558354+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
2015-08-04T09:10:40.558357+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2015-08-04T09:10:40.558356+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
2015-08-04T09:10:40.558349+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2015-08-04T09:10:40.558358+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2015-08-04T09:10:40.558348+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2015-08-04T09:10:40.558362+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
2015-08-04T09:10:40.558368+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2015-08-04T09:10:40.558363+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
2015-08-04T09:10:40.558373+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2015-08-04T09:10:40.558365+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2015-08-04T09:10:40.558370+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2015-08-04T09:10:40.558485+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
2015-08-04T09:10:40.558480+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
2015-08-04T09:10:40.558401+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
2015-08-04T09:10:40.558447+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
2015-08-04T09:10:40.558426+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2015-08-04T09:10:40.558483+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
2015-08-04T09:10:40.558510+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
2015-08-04T09:10:40.558508+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
2015-08-04T09:10:40.558491+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
```

I believe that the engine should be able to just use `root_path` without any prefix and it will go to it's own root path.

**Comment by jayroh** [comment]
Closed with Jim's PR

**Comment by jayroh** [comment]
Fixed with Jim's PR.
